### PR TITLE
add emoji and better description for 404 page

### PR DESCRIPTION
**Pull request by geekyahmed**
I added a better and informative way for the users to know that there is a missing page or content with emoji to support it.

### CODE REVIEW

**Comment by qthanh111** [comment]
#

**Comment by geekyahmed** [comment]
Hi @qthanh111 
Any problems ?

**Comment by geekyahmed** [comment]
@qthanh111  I hope you don't mind taking a look at the PR and getting back to me if there are any issues

**Comment by cramforce** [comment]
Let's keep this simple for now. I expect most sites to customize it themselves. Thanks for the PR!

**Comment by geekyahmed** [comment]
Ok I get.

**Pull request closed without merging**
